global:
  message: Welcome to customer service dev environment!!
server:
  port: 8085
message: Hello from Dev!
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customer_master
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    
      
